# Generated by Django 4.2.1 on 2023-05-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklib',
            name='radio_choice',
            field=models.CharField(choices=[('Brandnew', 'Brandnew'), ('Secondhand-Fair', 'Secondhand-Fair'), ('Secondhand-Poor', 'Secondhand-Poor')], max_length=20),
        ),
    ]
