# Generated by Django 4.2.7 on 2023-12-06 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0002_alter_booklib_radio_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklib',
            name='bookcover',
            field=models.ImageField(default='default_book_cover.jpg', upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='booklib',
            name='bookdocument',
            field=models.FileField(default='default_document.pdf', upload_to='book_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'csv'])]),
        ),
    ]
