# Generated by Django 4.2.7 on 2023-12-06 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0006_alter_booklib_bookcover_alter_booklib_bookdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklib',
            name='bookcover',
            field=models.ImageField(default='Harry_Potter.jpg', upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
